import * as path from 'path'
import { IResult, ISupportType } from './interfaces'
let _listFiledName: string[]
let _listDesc: string[]
let _listType: ISupportType
export namespace generateTs {
    export function generateCode(data: IResult, listFieldName: string[], listDesc: string[], listType: ISupportType): string {
        _listFiledName = listFieldName
        _listDesc = listDesc
        _listType = listType
        return `/** auto generated by tools/exlExport/main.js, do not modify! */
const DIC_ALL: { [fieldName: string]: { [fieldValue: string]: ${data.code.className}[] } } = {}
const LIST_ALL: ${data.code.className}[] = []
/**
 * ***file:*** ${path.basename(data.excel.inputFile)}
 *
 * ***sheet:*** ${data.excel.sheetName}
 * */
export class ${data.code.className} {
    ${generateGetters()}
    ${generateConstructor()}
    ${generateAppend(data)}
}
/**
 * ***file:*** ${path.basename(data.excel.inputFile)}
 *
 * ***sheet:*** ${data.excel.sheetName}
 * */
export namespace ${data.code.className}Provider {
    ${generateGetById(data)}
    ${generateGetOne(data)}
    ${generateGetFew(data)}
    ${generateGetAll(data)}
    ${generateNameSpaceGetters(data)}
}
`
    }

    function generateGetters(): string {
        const codes: string[] = []
        _listFiledName.forEach((fieldName: string, index: number): void => {
            codes.push(
                `/** ${_listDesc[index]} */
    get ${fieldName}(): ${_listType[index]} {
        return this._${fieldName}
    }`,
            )
        })
        return codes.join('\n    ')
    }

    function generateConstructor(): string {
        let code: string = 'constructor('
        _listFiledName.forEach((filedName: string, index: number): void => {
            if (index > 0) {
                code += ', '
            }
            code += 'private _' + filedName + ': ' + _listType[index]
        })
        code += ') { }'
        return code
    }

    function generateAppend(data: IResult): string {
        let dataType: string = '{ '
        _listFiledName.forEach((fieldName: string, index: number): void => {
            if (index > 0) {
                dataType += ', '
            }
            dataType += fieldName + ': ' + _listType[index]
        })
        dataType += ' }'

        return `static append(data: ${dataType}): void {
        if (${data.code.className}Provider.getById(data.${data.excel.idField})) { return }
        let ins: ${data.code.className} = new ${data.code.className}(data.${_listFiledName.join(', data.')})
        let dic: { [fieldValue: string]: ${data.code.className}[] }
        let list: ${data.code.className}[]
        let fieldValue: any
        [\'${_listFiledName.join('\', \'')}\'].forEach((fieldName: string): void => {
            dic = DIC_ALL[fieldName]
            if (!!!dic) {
                dic = {}
                DIC_ALL[fieldName] = dic
            }
            fieldValue = data[fieldName]
            list = dic[fieldValue]
            if (!!!list) {
                list = []
                dic[fieldValue] = list
            }
            list.push(ins)
        })
        LIST_ALL.push(ins)
    }`
    }

    function generateGetById(data: IResult): string {

        return `/**
     * 通过id获取一条数据
     * @param id 对应某条数据的id
     */
    export function getById(${data.excel.idField}: number | string): ${data.code.className} | undefined {
        return getOne('${data.excel.idField}', ${data.excel.idField})
    }`
    }

    function generateGetOne(data: IResult): string {
        return `/**
     * 获取符合字段名为[fieldName](参数fieldName提供的值),值为[fieldValue](参数fieldValue提供的值)的第一条数据
     * @param fieldName 字段名
     * @param fieldValue 要查找的值
     */
    export function getOne(fieldName: \'${_listFiledName.join('\' | \'')}\', fieldValue: any): ${data.code.className} | undefined {
        if (DIC_ALL[fieldName] && DIC_ALL[fieldName][fieldValue]) {
            return DIC_ALL[fieldName][fieldValue][0]
        }
        return undefined
    }`
    }

    function generateGetFew(data: IResult): string {
        return `/**
     * 获取符合字段名为[fieldName](参数fieldName提供的值),值为[fieldValue](参数fieldValue提供的值)的多条数据
     * @param fieldName 字段名
     * @param fieldValue 要查找的值
     * @param limite 长度限制,不传参数则代表取所有符合的数据
     */
    export function getFew(fieldName: \'${_listFiledName.join('\' | \'')}\', fieldValue: any, limite?: number): ${data.code.className}[] | undefined {
        if (DIC_ALL[fieldName] && DIC_ALL[fieldName][fieldValue]) {
            return DIC_ALL[fieldName][fieldValue].slice(0, limite)
        }
        return undefined
    }`
    }

    function generateGetAll(data: IResult): string {
        return `/** 获取所有数据 */
    export function getAll(): ${data.code.className}[] {
        return LIST_ALL
    }`
    }

    function generateNameSpaceGetters(data: IResult): string {
        const codes: string[] = []
        let code: string
        _listFiledName.forEach((fieldName: string, index: number): void => {
            if (fieldName !== data.excel.idField) {
                code = `/**
     * 获取某个[${data.excel.idField}](参数${data.excel.idField}提供的值)的${_listDesc[index]}
     * @param ${data.excel.idField} ${data.excel.idField}字段的值
     */
    export function ${fieldName}(${data.excel.idField}: number | string): ${_listType[index]} {
        return getById(${data.excel.idField}).${fieldName}
    }`
                codes.push(code)
            }
        })
        return codes.join('\n    ')
    }
}
