/** auto generated by tools/exlExport/main.js, do not modify! */
const DIC_ALL: { [fieldName: string]: { [fieldValue: string]: ExllangTable[] } } = {}
const LIST_ALL: ExllangTable[] = []

/**
 * ***file:*** 00.Lang.xlsx
 *
 * ***sheet:*** langTable
 * */
export class ExllangTable {

    static loadAll(option: {
        complete: (error: Error, resource: cc.JsonAsset[]) => void,
        completeScope?: any,
        progress?: (completeCount: number, totalCount: number, item: cc.AssetManager.RequestItem) => void,
        progressScope?: any
    }): void {
        cc.resources.load(['excelData/langTable'], cc.JsonAsset,
            (completeCount: number, totalCount: number, item: cc.AssetManager.RequestItem): void => {
                if (option.progress) {
                    option.progress.call(option.progressScope, completeCount, totalCount, item)
                }
            },
            (error: Error, resource: cc.JsonAsset | cc.JsonAsset[]): void => {
                let result: cc.JsonAsset[] = resource && (resource instanceof Array ? resource : [resource])
                if (error) {
                    console.error(error)
                } else if (result) {
                    result.forEach(res => {
                        switch (res.name) {
                            case 'langTable':
                                res.json.root.forEach((value: any): void => {
                                    ExllangTable.append(value)
                                });
                                break
                        }
                    })
                }
                if (option.complete) {
                    option.complete.call(option.completeScope, error, result)
                }
            },
        )
    }

    /** 描述key */
    get key(): string {
        return this._key
    }

    /** en-us(英文翻译) */
    get en_us(): string {
        return this._en_us
    }

    /** hi(印地翻译) */
    get hi(): string {
        return this._hi
    }

    /** id(印尼翻译) */
    get id(): string {
        return this._id
    }

    /** 巴西葡萄牙语 */
    get pt_br(): string {
        return this._pt_br
    }

    /** 阿拉伯 ar */
    get ar(): string {
        return this._ar
    }

    /** 泰语 */
    get th(): string {
        return this._th
    }

    /** 越南vi */
    get vi(): string {
        return this._vi
    }

    /** 中文 */
    get zh(): string {
        return this._zh
    }

    /** 西班牙 */
    get es(): string {
        return this._es
    }

    /** 土耳其 */
    get tr(): string {
        return this._tr
    }

    constructor(private _key: string, private _en_us: string, private _hi: string, private _id: string, private _pt_br: string, private _ar: string, private _th: string, private _vi: string, private _zh: string, private _es: string, private _tr: string) {
    }

    static append(data: {
        key: string,
        en_us: string,
        hi: string,
        id: string,
        pt_br: string,
        ar: string,
        th: string,
        vi: string,
        zh: string,
        es: string,
        tr: string
    }): void {
        if (ExllangTableProvider.getById(data.key)) {
            return
        }
        let ins: ExllangTable = new ExllangTable(data.key, data.en_us, data.hi, data.id, data.pt_br, data.ar, data.th, data.vi, data.zh, data.es, data.tr)
        let dic: { [fieldValue: string]: ExllangTable[] }
        let list: ExllangTable[]
        let fieldValue: any
        ['key', 'en_us', 'hi', 'id', 'pt_br', 'ar', 'th', 'vi', 'zh', 'es', 'tr'].forEach((fieldName: string): void => {
            dic = DIC_ALL[fieldName]
            if (!!!dic) {
                dic = {}
                DIC_ALL[fieldName] = dic
            }
            fieldValue = data[fieldName]
            list = dic[fieldValue]
            if (!!!list) {
                list = []
                dic[fieldValue] = list
            }
            list.push(ins)
        })
        LIST_ALL.push(ins)
    }
}

export namespace ExllangTableProvider {
    /**
     * 通过id获取一条数据
     * @param id 对应某条数据的id
     */
    export function getById(key: number | string): ExllangTable | undefined {
        return getOne('key', key)
    }

    /**
     * 获取符合字段名为[fieldName](参数fieldName提供的值),值为[fieldValue](参数fieldValue提供的值)的第一条数据
     * @param fieldName 字段名
     * @param fieldValue 要查找的值
     */
    export function getOne(fieldName: 'key' | 'en_us' | 'hi' | 'id' | 'pt_br' | 'ar' | 'th' | 'vi' | 'zh' | 'es' | 'tr', fieldValue: any): ExllangTable | undefined {
        if (DIC_ALL[fieldName] && DIC_ALL[fieldName][fieldValue]) {
            return DIC_ALL[fieldName][fieldValue][0]
        }
        return undefined
    }

    /**
     * 获取符合字段名为[fieldName](参数fieldName提供的值),值为[fieldValue](参数fieldValue提供的值)的多条数据
     * @param fieldName 字段名
     * @param fieldValue 要查找的值
     * @param limite 长度限制,不传参数则代表取所有符合的数据
     */
    export function getFew(fieldName: 'key' | 'en_us' | 'hi' | 'id' | 'pt_br' | 'ar' | 'th' | 'vi' | 'zh' | 'es' | 'tr', fieldValue: any, limite?: number): ExllangTable[] | undefined {
        if (DIC_ALL[fieldName] && DIC_ALL[fieldName][fieldValue]) {
            return DIC_ALL[fieldName][fieldValue].slice(0, limite)
        }
        return undefined
    }

    /** 获取所有数据 */
    export function getAll(): ExllangTable[] {
        return LIST_ALL
    }

    /**
     * 获取某个[key](参数key提供的值)的en-us(英文翻译)
     * @param key key字段的值
     */
    export function en_us(key: number | string): string {
        return getById(key).en_us
    }

    /**
     * 获取某个[key](参数key提供的值)的hi(印地翻译)
     * @param key key字段的值
     */
    export function hi(key: number | string): string {
        return getById(key).hi
    }

    /**
     * 获取某个[key](参数key提供的值)的id(印尼翻译)
     * @param key key字段的值
     */
    export function id(key: number | string): string {
        return getById(key).id
    }

    /**
     * 获取某个[key](参数key提供的值)的巴西葡萄牙语
     * @param key key字段的值
     */
    export function pt_br(key: number | string): string {
        return getById(key).pt_br
    }

    /**
     * 获取某个[key](参数key提供的值)的阿拉伯 ar
     * @param key key字段的值
     */
    export function ar(key: number | string): string {
        return getById(key).ar
    }

    /**
     * 获取某个[key](参数key提供的值)的泰语
     * @param key key字段的值
     */
    export function th(key: number | string): string {
        return getById(key).th
    }

    /**
     * 获取某个[key](参数key提供的值)的越南vi
     * @param key key字段的值
     */
    export function vi(key: number | string): string {
        return getById(key).vi
    }

    /**
     * 获取某个[key](参数key提供的值)的中文
     * @param key key字段的值
     */
    export function zh(key: number | string): string {
        return getById(key).zh
    }

    /**
     * 获取某个[key](参数key提供的值)的西班牙
     * @param key key字段的值
     */
    export function es(key: number | string): string {
        return getById(key).es
    }

    /**
     * 获取某个[key](参数key提供的值)的土耳其
     * @param key key字段的值
     */
    export function tr(key: number | string): string {
        return getById(key).tr
    }
}
